apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lmlu4nzbl-nodejs
  janus-idp.io/tekton: lmlu4nzbl-nodejs
  backstage.io/kubernetes-id: lmlu4nzbl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lmlu4nzbl-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
