apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lmlu4nzbl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lmlu4nzbl-nodejs 
  name: lmlu4nzbl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lmlu4nzbl-nodejs 
